### PR TITLE
Jenkins 2.7.4 LTS

### PR DESCRIPTION
**Pull request by anton-kasperovich**
Description was provided in separate PR's #19 and #21 

In general, the main goal is to upgrade Jenkins to the new 2.7.4 LTS version with almost all plugins.

### CODE REVIEW

**Comment by dsingh07** [comment]
Hi @anton-kasperovich 

I have spun up an ADOP instance with the pre-release tag for the new Jenkins image and comes up fine without any issues.
I have tested the following cases successfully:
- Loading the platform
- Creating a Tomcat environment
- Running through the Java pipeline successfully
- Running through the Docker pipeline successfully
- Loading the chef platform extension
- Logging with users with only viewer/developer permissions in a project and only having the correct stuff visible to me
- Logging with users with only viewer/developer permissions in a workspace and only having the correct stuff visible to me

Various issues in old Jenkins which now seem to be fixed:
- Clicking the console output button on job in the pipeline view works
- Boxes are appropriately sized in the pipeline view for each job
- The Jenkins home link in the cucumber report works now

Only issue that I encountered was loading the cartridge collection using the "Load_Cartridge_Collection" job https://raw.githubusercontent.com/Accenture/adop-doa-materials/master/Cartridge_Collections/doa_cartridge_collection.json
Got back some groovy errors:
```groovy
java.io.NotSerializableException: groovy.json.internal.LazyMap
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:860)
	at org.jboss.marshalling.river.BlockMarshaller.doWriteObject(BlockMarshaller.java:65)
	at org.jboss.marshalling.river.BlockMarshaller.writeObject(BlockMarshaller.java:56)
	at org.jboss.marshalling.MarshallerObjectOutputStream.writeObjectOverride(MarshallerObjectOutputStream.java:50)
	at org.jboss.marshalling.river.RiverObjectOutputStream.writeObjectOverride(RiverObjectOutputStream.java:179)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344)
	at java.util.HashMap.internalWriteEntries(HashMap.java:1785)
	at java.util.HashMap.writeObject(HashMap.java:1362)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.marshalling.reflect.SerializableClass.callWriteObject(SerializableClass.java:271)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:976)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:854)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1032)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:988)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:854)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1032)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:988)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:967)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:967)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:854)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1032)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:988)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:967)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:854)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1032)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:988)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:967)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:854)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1032)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:988)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:967)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:854)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1032)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:988)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:854)
	at org.jboss.marshalling.river.BlockMarshaller.doWriteObject(BlockMarshaller.java:65)
	at org.jboss.marshalling.river.BlockMarshaller.writeObject(BlockMarshaller.java:56)
	at org.jboss.marshalling.MarshallerObjectOutputStream.writeObjectOverride(MarshallerObjectOutputStream.java:50)
	at org.jboss.marshalling.river.RiverObjectOutputStream.writeObjectOverride(RiverObjectOutputStream.java:179)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344)
	at java.util.TreeMap.writeObject(TreeMap.java:2438)
	at sun.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.marshalling.reflect.SerializableClass.callWriteObject(SerializableClass.java:271)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:976)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:854)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1032)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:988)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:854)
	at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
	at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:111)
	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.writeObject(RiverWriter.java:132)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:429)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:408)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:356)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:78)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:236)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:224)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: an exception which occurred:
	in field locals
	in field parent
	in field parent
	in field caller
	in field e
	in field program
	in field threads
	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@7b8907e3l
```

This may require a fix Platform Management or enable some Groovy permissions in scriptApproval.xml

**Comment by dsingh07** [comment]
Seems the issue could be: 
https://github.com/anton-kasperovich/adop-jenkins/blob/2.0/resources/scriptApproval.xml#L2
versus 
https://github.com/anton-kasperovich/adop-jenkins/blob/2.0/resources/plugins.txt#L67

**Comment by anton-kasperovich** [comment]
Found working solution for Jenkins 2.* http://stackoverflow.com/a/38439681 , but, because we don't have releases for Platform Management, i can't update it as it will break everyone's currently working Jenkins 1.* if they for some reason would decide to re-load platform management. I do found some solutions how to make it works on both version of Jenkins, but still it's require changing security policy to allow me to use some Groovy methods, which is not allowed to use by default. Long story short, i'm trying to rewrite Cartridge_Collection and Platform_Collection jobs to support legacy and new version of Jenkins.

**Comment by anton-kasperovich** [comment]
Known issues:
- scriptApproval.xml contains wrong version of Security Plugin
- Load_Cartridge_Collection fails because of "groovy.json.JsonSlurper"
- Load_Platform_Extension_Collection fails because of "groovy.json.JsonSlurper"
- Loading "adop-cartridge-doa-m7-m8" cartridge fails because of groovy script file name "ERROR: invalid script name 'doa_labs-m7-m8.groovy; script names may only contain letters, digits and underscores, but may not start with a digit"

**Comment by nickdgriffin** [comment]
Dependencies merged.

**Comment by dsingh07** [comment]
Tested old cases with new changes implemented:
- Earlier issue with Load Cartridge Collection is now resolved
- Re-implemented version of Load Platform Extension Collection also works as expected
- All cases that were described in the comment above earlier still work as expected

Have also tested the changes to loading collections in Jenkins 1.* and it works as expected

**Comment by nickdgriffin** [comment]
I've also tested out:
* Full pipeline for FOSS Java
* Loading a cartridge collection
* Loading a platform extension collection

I need to also test out the CLI commands that call Jenkins to make sure they still work.

**Comment by anton-kasperovich** [comment]
@nickdgriffin i have tested CLI from TravisCI yaml file:

**./adop workspace -w Travis create**:
```
root@scw-928090-adop:/data/adop-docker-compose# ./adop workspace -w Travis create
Loading the credentials..
Creating the workspace ...
Waiting for job to complete...
Checking if job has been built previously or if build has initialised...
Checking if build is in queue...
Workspace 'Travis' has been created successfully.
```

**./adop project -p TestProject -w Travis**
```
root@scw-928090-adop:/data/adop-docker-compose# ./adop project -p TestProject -w Travis create
TestProject Travis
Loading the credentials..
Creating the project space ...
Waiting for job to complete...
Checking if job has been built previously or if build has initialised...
Checking if build is in queue...
Project 'TestProject' has been created successfully in workspace Travis.
```

Both finished successfully.

screen shot 2016-09-29 at 8 44 40 am

**Comment by nickdgriffin** [comment]
Great, I think that's all I had in mind!

**Pull request merged**
