### PR TITLE
Add env variable to check if ldap is external or internal. Default is internal.

### PR DESCRIPTION
**Pull request by marisbahtins**
Added "ENABLE_INTERNAL_LDAP" environment variable which tells what LDAP connection we have (external or internal). This environment variable is used in [adop-platform-managment](https://github.com/Accenture/adop-platform-management/pull/50) repository.

### CODE REVIEW

**Comment by dsingh07** [comment]
Do we need to inject this env variable into Jenkins as a system environment variable so that it can be consumed by jobs? E.g. https://github.com/Accenture/adop-jenkins/blob/master/resources/init.groovy.d/adop_general.groovy#L28

**Comment by marisbahtins** [comment]
Renamed "ENABLE_INTERNAL_LDAP" to "LDAP_IS_MODIFIABLE" variable and explained the meaning of it the README.md

**Comment by SachinKSingh28** [comment]
I have tested this PR and it works as expected. Need to verify documentation.

**Comment by SachinKSingh28** [comment]
I have tested this change. LGTM.

**Pull request merged**
