### PR TITLE
Adding plugins

### PR DESCRIPTION
**Pull request by kramos**
Adding Metrics plugin and Build File Analyser.  Upgrading Claim to support BFA.

### CODE REVIEW

**Comment by kramos** [comment]
We should define a set of jobs that contributors should regression test Jenkins changes against.

**Comment by anton-kasperovich** [comment]
Hi @kramos this is actually tricky PR, 'cause i think we can't bake all possible plugins inside an image, we should agree on which types of plugins (maybe some criteria) can be merged and which is not. What do you think @nickdgriffin @SachinKSingh28 ?

**Comment by kramos** [comment]
This is a blast from the past! Thanks for looking at it @anton-kasperovich 

The justification were:
 1 Claim upgrade so that Build Failure Analyser (problem management for failed jobs) works
 2 Metrics produces good metrics and needs Jacson I think
 3 Extended choice so that the dynamic cartridge list loader I proposed a while back works.

I'm not desperate for any of these now but I do think number 1 above is very valid still.

I guess this PR should sit here until others  +1 it.

**Comment by kramos** [comment]
Lost interest in this.  Closing

**Pull request closed without merging**
