### PR TITLE
Adding blue ocean plugin and its dependencies

### PR DESCRIPTION
**Pull request by lykabernardo**
* Adding blue ocean plugin and its dependencies
* Updating jackson2-api plugin version for blue ocean
* Tested with ADOP/C

### CODE REVIEW

**Comment by lykabernardo** [comment]
Hi @dsingh07 i had to delete the downstream branch to create a separate PR for the sonar token automation. I can recreate this PR if needed. Please let me know.

**Comment by dsingh07** [comment]
Hi @lykabernardo yes I think that would be preferable whenever you have time, thanks!

**Comment by lykabernardo** [comment]
Hi @dsingh07 please see https://github.com/Accenture/adop-jenkins/pull/64 for the new PR.

**Comment by dsingh07** [comment]
Thanks @lykabernardo closing this PR.

**Pull request closed without merging**
